# Generated by Django 3.0.5 on 2020-04-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_articletext'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='input_files')),
                ('input_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='output_files')),
                ('output_name', models.CharField(max_length=100)),
                ('input_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.InputFile')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleText',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
