# Generated by Django 3.0.5 on 2020-04-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20200423_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutputFile',
        ),
    ]
